name: Auto Update Configs

on:
  schedule:
    - cron: '0 * * * *'   # каждый час
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download configs
        run: |
          curl -o Vless_list.txt https://raw.githubusercontent.com/PrinceVSFX/Vless-Configs/main/Vless_list.txt

      - name: Commit changes
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "auto update configs" || echo "no changes"
          git push
